title: Blog di Simona
author: SimonaPiz
email: simona.pizio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Questo è un blog di esercitazione su GitHub pages. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
